# Scrip Name: mongoDB_load_xaa700m_row.sh
# Purpose:  Load 700 million rows into mongoDB (a three replica cluster)

# Note: the data is stored on the local driver(xaa700m_row.csv, which is generated by:
# "genrand 700000000 71"

# Command Line: "nohup mongoDB_load_xaa700m_row.sh > mongoDB_load_xaa700m_row.sh.out &"

t1=`date +%s`
echo -e "\n==> Starting time is t1: $t1, `date` \n"


mongoimport --db jagdb --collection xaa700m_row  --type csv --file /home/andrew/QA_HOME/test_100milion/xaa700m_row.csv --headerline

# Calc the time required:
t2=`date +%s`
echo -e "\n\n ===> Ending time is t2: $t2, `date`"

let deltatime=t2-t1
let hours=deltatime/3600
let minutes=(deltatime/60)%60
let seconds=deltatime%60

echo -e "\nTotal time in second: $deltatime"
printf "Total time in hour:min:sec: %d:%02d:%02d \n" $hours $minutes $seconds
